languaje: node_js
cache: 
  direcctories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true,
  skip-cleanup : true
  keep-history: true
  gitgub-token: $GITHUB_TOKEN
  local-dir: dist/
  target-brack: gh-pages
  commit_message: "Deploy Release"
  on:
  branch: master